apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smart-crawler
    kind: sc-geostrategic-agoda-consume
  name: sc-geostrategic-agoda-consume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-crawler
      kind: sc-geostrategic-agoda-consume
  template:
    metadata:
      labels:
        app: smart-crawler
        kind: sc-geostrategic-agoda-consume
    spec:
      hostAliases:
        - ip: "10.12.1.101"
          hostnames:
            - "kafka01.research.ai"
        - ip: "10.12.1.102"
          hostnames:
            - "kafka02.research.ai"
        - ip: "10.12.1.103"
          hostnames:
            - "kafka03.research.ai"
        - ip: "192.168.24.201"
          hostnames:
            - "kafka01.production02.bt"
        - ip: "192.168.24.202"
          hostnames:
            - "kafka02.production02.bt"
        - ip: "192.168.24.203"
          hostnames:
            - "kafka03.production02.bt"
        - ip: "192.168.24.204"
          hostnames:
            - "kafka04.production02.bt"
        - ip: "192.168.24.205"
          hostnames:
            - "kafka05.production02.bt"
        - ip: "192.168.24.206"
          hostnames:
            - "kafka06.production02.bt"
      containers:
        - name: sc-geostrategic-agoda-consume
          image: 192.168.202.50/crawler/smart-crawler/engine-romy:4.1.9
          command:
            - /bin/sh
            - -c
            - engine_romy --kafka --bootstrap='kafka01.research.ai,kafka02.research.ai,kafka03.research.ai' --topic=data-knowledge-repo-general_10 data_icc agoda --proxy watch_beanstalk
          imagePullPolicy: IfNotPresent
